dependencies:
  integration_app:
    name: OpenProject Integration
    url: https://apps.nextcloud.com/apps/integration_openproject
    min_version: 2.11.0
  team_folders_app:
    name: Team folders
    url: https://apps.nextcloud.com/apps/groupfolders
    min_version: 20.1.7
